---
- name: mini-project-setup
  hosts: servers
  become: true

  tasks: 

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker & Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
